//! File merge utilities for `crosslink init` — gitignore, MCP, provider config,
//! and managed instruction blocks.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;
use toml_edit::{DocumentMut, Item};

// Section markers for idempotent gitignore management
pub(super) const GITIGNORE_SECTION_START: &str =
    "# === Crosslink managed (do not edit between markers) ===";
pub(super) const GITIGNORE_SECTION_END: &str = "# === End crosslink managed ===";
pub(super) const AGENTS_SECTION_START: &str = "<!-- crosslink:managed:start -->";
pub(super) const AGENTS_SECTION_END: &str = "<!-- crosslink:managed:end -->";

const GITIGNORE_MANAGED_SECTION: &str = "\
# .crosslink/ — machine-local state (never commit)
.crosslink/issues.db
.crosslink/issues.db-wal
.crosslink/issues.db-shm
.crosslink/agent.json
.crosslink/session.json
.crosslink/daemon.pid
.crosslink/daemon.log
.crosslink/last_test_run
.crosslink/.active-issue
.crosslink/.last-hydrated-ref
.crosslink/.promoted-uuids
.crosslink/promotion-log.json
.crosslink/hub-v3-shadow-stats.json
.crosslink/sentinel.log
.crosslink/keys/
.crosslink/.hub-cache/
.crosslink/.knowledge-cache/
.crosslink/.cache/
.crosslink/runtime/
.crosslink/init-manifest.json
.crosslink/init-manifest.json.tmp
.crosslink/hook-config.local.json
.crosslink/integrations/
.crosslink/rules.local/

# .crosslink/ — DO track these (project-level policy):
#   .crosslink/hook-config.json   — shared team configuration
#   .crosslink/rules/             — project coding standards
#   .crosslink/.gitignore         — inner gitignore for agent files

# .claude/ — auto-generated by crosslink init (not project source)
.claude/commands/
.claude/skills/

# .claude/ — DO track these (if manually configured):
#   .claude/settings.json         — Claude Code project settings
#   .claude/settings.local.json is per-developer, ignore separately if needed

# Codex generated discovery assets (project-local integrations)
.agents/skills/
.codex/hooks.json

# Codex config and AGENTS.md may contain user content and are intentionally tracked.
# Crosslink merges only its owned sections into them.
";

/// Write or update a managed section in the project root `.gitignore`.
///
/// The section is delimited by `GITIGNORE_SECTION_START` / `GITIGNORE_SECTION_END` markers.
/// On first run the section is appended; on subsequent runs the existing section is replaced
pub(super) fn write_root_gitignore(project_root: &Path) -> Result<()> {
    let gitignore_path = project_root.join(".gitignore");

    let managed_block =
        format!("{GITIGNORE_SECTION_START}\n{GITIGNORE_MANAGED_SECTION}{GITIGNORE_SECTION_END}\n");

    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();

    let new_content = if let (Some(start_pos), Some(end_pos)) = (
        existing.find(GITIGNORE_SECTION_START),
        existing.find(GITIGNORE_SECTION_END),
    ) {
        // Replace existing managed section in-place
        let before = &existing[..start_pos];
        let after = &existing[end_pos + GITIGNORE_SECTION_END.len()..];
        // Strip leading newline from `after` so we don't accumulate blank lines
        let after = after.strip_prefix('\n').unwrap_or(after);
        format!("{before}{managed_block}{after}")
    } else {
        // Append new section (with a blank separator if file has content)
        if existing.is_empty() {
            managed_block
        } else {
            let separator = if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            format!("{existing}{separator}{managed_block}")
        }
    };

    fs::write(&gitignore_path, new_content).context("Failed to write .gitignore")?;
    Ok(())
}

/// Merge crosslink's MCP server entries into an existing `.mcp.json`, or create it fresh.
use super::{
    AGENTS_MD, CODEX_CONFIG_TOML, CODEX_HOOKS_JSON, MCP_JSON, PYTHON_PREFIX_PLACEHOLDER,
    SETTINGS_JSON,
};

pub(super) fn write_mcp_json_merged(mcp_path: &Path) -> Result<Vec<String>> {
    let embedded: serde_json::Value = serde_json::from_str(MCP_JSON)
        .context("embedded MCP_JSON is not valid JSON — this is a build defect")?;
    let src_servers = embedded
        .get("mcpServers")
        .and_then(|v| v.as_object())
        .context("embedded MCP_JSON missing mcpServers object — this is a build defect")?;

    let mut obj = match fs::read_to_string(mcp_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing .mcp.json at {} contains invalid JSON — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing .mcp.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => return Err(anyhow::Error::from(e).context("Failed to read existing .mcp.json")),
    };

    let mut dest_map = match obj.remove("mcpServers") {
        Some(serde_json::Value::Object(map)) => map,
        Some(_) => anyhow::bail!(
            "Existing .mcp.json has a non-object mcpServers value — \
             refusing to overwrite. Fix or remove it, then retry."
        ),
        None => serde_json::Map::new(),
    };

    // Retire Crosslink's removed downloader registration during migration.
    dest_map.remove("crosslink-safe-fetch");

    let mut warnings = Vec::new();
    for (key, value) in src_servers {
        if dest_map.contains_key(key) {
            warnings.push(format!(
                "Warning: overwriting existing mcpServers entry \"{key}\" with crosslink default"
            ));
        }
        dest_map.insert(key.clone(), value.clone());
    }

    obj.insert("mcpServers".into(), serde_json::Value::Object(dest_map));

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize .mcp.json")?;
    output.push('\n');
    fs::write(mcp_path, output).context("Failed to write .mcp.json")?;
    Ok(warnings)
}

/// Merge crosslink's default `allowedTools` into an existing `.claude/settings.json`,
/// or create it fresh.  Hooks are always overwritten (they are crosslink-managed),
/// but user-added `allowedTools` entries are preserved.
///
/// The `python_prefix` is substituted into hook commands via the `__PYTHON_PREFIX__`
pub(super) fn write_settings_json_merged(settings_path: &Path, python_prefix: &str) -> Result<()> {
    let template_raw = SETTINGS_JSON.replace(PYTHON_PREFIX_PLACEHOLDER, python_prefix);
    let template: serde_json::Value = serde_json::from_str(&template_raw).context(
        "embedded SETTINGS_JSON is not valid JSON after substitution — this is a build defect",
    )?;

    let embedded_tools: Vec<String> = template
        .get("allowedTools")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    let mut obj = match fs::read_to_string(settings_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing settings.json at {} contains invalid JSON — \
                         refusing to overwrite. Fix or remove it, then retry.",
                    settings_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing settings.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    settings_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => {
            return Err(anyhow::Error::from(e).context("Failed to read existing settings.json"))
        }
    };

    // Merge allowedTools: union of existing entries + embedded defaults (no duplicates)
    let mut tools: Vec<String> = obj
        .get("allowedTools")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    for tool in &embedded_tools {
        if !tools.contains(tool) {
            tools.push(tool.clone());
        }
    }

    obj.insert(
        "allowedTools".into(),
        serde_json::Value::Array(tools.into_iter().map(serde_json::Value::String).collect()),
    );

    // Overwrite hooks (crosslink-managed) and enableAllProjectMcpServers
    if let Some(hooks) = template.get("hooks") {
        obj.insert("hooks".into(), hooks.clone());
    }
    if let Some(enable) = template.get("enableAllProjectMcpServers") {
        obj.insert("enableAllProjectMcpServers".into(), enable.clone());
    }

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize settings.json")?;
    output.push('\n');
    fs::write(settings_path, output).context("Failed to write settings.json")?;
    Ok(())
}

/// Merge Crosslink hook groups while preserving unrelated Codex hook groups and
/// all unknown top-level JSON keys.
pub(super) fn write_codex_hooks_merged(hooks_path: &Path, python_prefix: &str) -> Result<()> {
    let template_raw = CODEX_HOOKS_JSON.replace(PYTHON_PREFIX_PLACEHOLDER, python_prefix);
    let template: serde_json::Value = serde_json::from_str(&template_raw)
        .context("embedded Codex hooks.json is invalid — this is a build defect")?;
    let template_hooks = template
        .get("hooks")
        .and_then(serde_json::Value::as_object)
        .context("embedded Codex hooks.json has no hooks object")?;

    let mut root = match fs::read_to_string(hooks_path) {
        Ok(raw) => serde_json::from_str::<serde_json::Value>(&raw).with_context(|| {
            format!(
                "Existing Codex hooks at {} contain invalid JSON — refusing to overwrite",
                hooks_path.display()
            )
        })?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => serde_json::json!({}),
        Err(error) => return Err(error).context("Failed to read Codex hooks.json"),
    };
    let root_obj = root
        .as_object_mut()
        .context("Existing Codex hooks.json is not an object")?;
    let hooks = root_obj
        .entry("hooks")
        .or_insert_with(|| serde_json::json!({}))
        .as_object_mut()
        .context("Existing Codex hooks value is not an object")?;

    for (event, managed_groups) in template_hooks {
        let mut retained = hooks
            .remove(event)
            .and_then(|value| value.as_array().cloned())
            .unwrap_or_default();
        retained.retain(|group| {
            !group
                .get("description")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|description| description.starts_with("crosslink:"))
        });
        retained.extend(managed_groups.as_array().cloned().unwrap_or_default());
        hooks.insert(event.clone(), serde_json::Value::Array(retained));
    }

    let output = format!("{}\n", serde_json::to_string_pretty(&root)?);
    fs::write(hooks_path, output).context("Failed to write Codex hooks.json")
}

/// Merge only Crosslink's MCP tables into Codex config, retaining comments,
/// ordering, profiles, unknown keys, and unrelated MCP servers.
pub(super) fn write_codex_config_merged(config_path: &Path) -> Result<()> {
    let template = CODEX_CONFIG_TOML
        .parse::<DocumentMut>()
        .context("embedded Codex config.toml is invalid — this is a build defect")?;
    let mut document = match fs::read_to_string(config_path) {
        Ok(raw) => raw.parse::<DocumentMut>().with_context(|| {
            format!(
                "Existing Codex config at {} contains invalid TOML — refusing to overwrite",
                config_path.display()
            )
        })?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => DocumentMut::new(),
        Err(error) => return Err(error).context("Failed to read Codex config.toml"),
    };

    if document.get("mcp_servers").is_none() {
        document["mcp_servers"] = Item::Table(toml_edit::Table::new());
    }
    let destination = document["mcp_servers"]
        .as_table_like_mut()
        .context("Existing Codex config has non-table mcp_servers — refusing to overwrite")?;
    let source = template["mcp_servers"]
        .as_table_like()
        .context("embedded Codex config has no mcp_servers table")?;
    for (name, item) in source.iter() {
        destination.insert(name, item.clone());
    }

    fs::write(config_path, document.to_string()).context("Failed to write Codex config.toml")
}

/// Insert or repair exactly one Crosslink-owned block in AGENTS.md.
pub(super) fn write_agents_md_merged(agents_path: &Path) -> Result<()> {
    let existing = fs::read_to_string(agents_path).unwrap_or_default();
    let replacement = AGENTS_MD.trim_end();
    let content = match existing.find(AGENTS_SECTION_START) {
        Some(first_start) => {
            let mut suffix = String::new();
            let mut cursor = first_start;
            while let Some(relative_start) = existing[cursor..].find(AGENTS_SECTION_START) {
                let start = cursor + relative_start;
                suffix.push_str(&existing[cursor..start]);
                let after_start = start + AGENTS_SECTION_START.len();
                let Some(relative_end) = existing[after_start..].find(AGENTS_SECTION_END) else {
                    // Preserve text following a malformed marker while removing
                    // the reserved marker itself; a fresh valid block is inserted.
                    suffix.push_str(&existing[after_start..]);
                    cursor = existing.len();
                    break;
                };
                cursor = after_start + relative_end + AGENTS_SECTION_END.len();
            }
            suffix.push_str(&existing[cursor..]);
            format!("{}{}{}", &existing[..first_start], replacement, suffix)
        }
        _ if existing.is_empty() => format!("{replacement}\n"),
        _ => {
            let separator = if existing.ends_with("\n\n") {
                ""
            } else if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            format!("{existing}{separator}{replacement}\n")
        }
    };
    fs::write(agents_path, content).context("Failed to write AGENTS.md")
}

pub(super) fn agents_managed_hash(path: &Path) -> Result<Option<String>> {
    let raw = match fs::read_to_string(path) {
        Ok(raw) => raw,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error).context("Failed to read AGENTS.md"),
    };
    let Some(start) = raw.find(AGENTS_SECTION_START) else {
        return Ok(None);
    };
    let Some(relative_end) = raw[start..].find(AGENTS_SECTION_END) else {
        return Ok(None);
    };
    let end = start + relative_end + AGENTS_SECTION_END.len();
    Ok(Some(super::manifest::sha256_hex(&raw[start..end])))
}
